package com.nc.ws.impl.cxf;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.nc.ws.intf.cxf.CardHolderProfileRPCENCService;

import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-11-20T19:13:03.997+05:30
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "CardHolderProfileRPCENCServiceImplService", 
                  wsdlLocation = "http://localhost:9001/ws/rpcenc?wsdl",
                  targetNamespace = "http://impl.ws.nc.com/") 
public class CardHolderProfileRPCENCServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.nc.com/", "CardHolderProfileRPCENCServiceImplService");
    public final static QName CardHolderProfileRPCENCServiceImplPort = new QName("http://impl.ws.nc.com/", "CardHolderProfileRPCENCServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9001/ws/rpcenc?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CardHolderProfileRPCENCServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9001/ws/rpcenc?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CardHolderProfileRPCENCServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CardHolderProfileRPCENCServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CardHolderProfileRPCENCServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CardHolderProfileRPCENCServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CardHolderProfileRPCENCServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CardHolderProfileRPCENCServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CardHolderProfileRPCENCService
     */
    @WebEndpoint(name = "CardHolderProfileRPCENCServiceImplPort")
    public CardHolderProfileRPCENCService getCardHolderProfileRPCENCServiceImplPort() {
        return super.getPort(CardHolderProfileRPCENCServiceImplPort, CardHolderProfileRPCENCService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CardHolderProfileRPCENCService
     */
    @WebEndpoint(name = "CardHolderProfileRPCENCServiceImplPort")
    public CardHolderProfileRPCENCService getCardHolderProfileRPCENCServiceImplPort(WebServiceFeature... features) {
        return super.getPort(CardHolderProfileRPCENCServiceImplPort, CardHolderProfileRPCENCService.class, features);
    }

}
