package com.nc.ws.intf.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-11-22T11:06:47.721+05:30
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://intf.ws.nc.com/", name = "CardHolderProfileDOCLITService")
@XmlSeeAlso({ObjectFactory.class})
public interface CardHolderProfileDOCLITService {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://intf.ws.nc.com/CardHolderProfileDOCLITService/checkProfileRequest", output = "http://intf.ws.nc.com/CardHolderProfileDOCLITService/checkProfileResponse")
    @RequestWrapper(localName = "checkProfile", targetNamespace = "http://intf.ws.nc.com/", className = "com.nc.ws.intf.CheckProfile")
    @WebMethod
    @ResponseWrapper(localName = "checkProfileResponse", targetNamespace = "http://intf.ws.nc.com/", className = "com.nc.ws.intf.CheckProfileResponse")
    public com.nc.ws.intf.cxf.CardHolder checkProfile(
        @WebParam(name = "arg0", targetNamespace = "")
        com.nc.ws.intf.cxf.CardHolder arg0
    );
}
