package com.nc.ws.impl.cxf;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.nc.ws.intf.cxf.CardHolderProfileRPCLITService;

import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-11-22T11:04:53.931+05:30
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "CardHolderProfileRPCLITServiceImplService", 
                  wsdlLocation = "http://localhost:9002/ws/rpclit?wsdl",
                  targetNamespace = "http://impl.ws.nc.com/") 
public class CardHolderProfileRPCLITServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.nc.com/", "CardHolderProfileRPCLITServiceImplService");
    public final static QName CardHolderProfileRPCLITServiceImplPort = new QName("http://impl.ws.nc.com/", "CardHolderProfileRPCLITServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9002/ws/rpclit?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CardHolderProfileRPCLITServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9002/ws/rpclit?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CardHolderProfileRPCLITServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CardHolderProfileRPCLITServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CardHolderProfileRPCLITServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CardHolderProfileRPCLITServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CardHolderProfileRPCLITServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CardHolderProfileRPCLITServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CardHolderProfileRPCLITService
     */
    @WebEndpoint(name = "CardHolderProfileRPCLITServiceImplPort")
    public CardHolderProfileRPCLITService getCardHolderProfileRPCLITServiceImplPort() {
        return super.getPort(CardHolderProfileRPCLITServiceImplPort, CardHolderProfileRPCLITService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CardHolderProfileRPCLITService
     */
    @WebEndpoint(name = "CardHolderProfileRPCLITServiceImplPort")
    public CardHolderProfileRPCLITService getCardHolderProfileRPCLITServiceImplPort(WebServiceFeature... features) {
        return super.getPort(CardHolderProfileRPCLITServiceImplPort, CardHolderProfileRPCLITService.class, features);
    }

}
