package com.nc.ws.intf.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-11-22T11:04:53.789+05:30
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://intf.ws.nc.com/", name = "CardHolderProfileRPCLITService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface CardHolderProfileRPCLITService {

    @WebResult(name = "return", targetNamespace = "http://intf.ws.nc.com/", partName = "return")
    @Action(input = "http://intf.ws.nc.com/CardHolderProfileRPCLITService/checkProfileRequest", output = "http://intf.ws.nc.com/CardHolderProfileRPCLITService/checkProfileResponse")
    @WebMethod
    public CardHolder checkProfile(
        @WebParam(partName = "arg0", name = "arg0")
        CardHolder arg0
    );
}
