
package com.nc.ws.impl.metro;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CardHolderProfileDOCLITServiceImplService", targetNamespace = "http://impl.ws.nc.com/", wsdlLocation = "http://localhost:9003/ws/doclit?wsdl")
public class CardHolderProfileDOCLITServiceImplService
    extends Service
{

    private final static URL CARDHOLDERPROFILEDOCLITSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CARDHOLDERPROFILEDOCLITSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CARDHOLDERPROFILEDOCLITSERVICEIMPLSERVICE_QNAME = new QName("http://impl.ws.nc.com/", "CardHolderProfileDOCLITServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9003/ws/doclit?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARDHOLDERPROFILEDOCLITSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CARDHOLDERPROFILEDOCLITSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CardHolderProfileDOCLITServiceImplService() {
        super(__getWsdlLocation(), CARDHOLDERPROFILEDOCLITSERVICEIMPLSERVICE_QNAME);
    }

    public CardHolderProfileDOCLITServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARDHOLDERPROFILEDOCLITSERVICEIMPLSERVICE_QNAME, features);
    }

    public CardHolderProfileDOCLITServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CARDHOLDERPROFILEDOCLITSERVICEIMPLSERVICE_QNAME);
    }

    public CardHolderProfileDOCLITServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARDHOLDERPROFILEDOCLITSERVICEIMPLSERVICE_QNAME, features);
    }

    public CardHolderProfileDOCLITServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CardHolderProfileDOCLITServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CardHolderProfileDOCLITService
     */
    @WebEndpoint(name = "CardHolderProfileDOCLITServiceImplPort")
    public CardHolderProfileDOCLITService getCardHolderProfileDOCLITServiceImplPort() {
        return super.getPort(new QName("http://impl.ws.nc.com/", "CardHolderProfileDOCLITServiceImplPort"), CardHolderProfileDOCLITService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CardHolderProfileDOCLITService
     */
    @WebEndpoint(name = "CardHolderProfileDOCLITServiceImplPort")
    public CardHolderProfileDOCLITService getCardHolderProfileDOCLITServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.ws.nc.com/", "CardHolderProfileDOCLITServiceImplPort"), CardHolderProfileDOCLITService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARDHOLDERPROFILEDOCLITSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CARDHOLDERPROFILEDOCLITSERVICEIMPLSERVICE_EXCEPTION;
        }
        return CARDHOLDERPROFILEDOCLITSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
