
package com.nc.ws.impl.metro;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

import com.nc.ws.intf.metro.CardHolder;
import com.nc.ws.intf.metro.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CardHolderProfileRPCLITService", targetNamespace = "http://intf.ws.nc.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CardHolderProfileRPCLITService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.nc.ws.intf.CardHolder
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://intf.ws.nc.com/CardHolderProfileRPCLITService/checkProfileRequest", output = "http://intf.ws.nc.com/CardHolderProfileRPCLITService/checkProfileResponse")
    public CardHolder checkProfile(
        @WebParam(name = "arg0", partName = "arg0")
        CardHolder arg0);

}
